neo4j:
  restart: always
  image: neo4j:2.3.2-enterprise
  container_name: neo4j
  net: ${NETWORK}
  environment:
    - NEO4J_AUTH=none
    - elastic="http://elastic_container"
  volumes:
    - ./neo4j/conf:/conf
    - ./neo4j/plugins:/plugins
    - ./neo4j/data/import:/data/import
  ports:
    - "7474:7474"
elastic:
  image: elasticsearch:2.2.1
  restart: always
  net: ${NETWORK}
  container_name: elastic_container
  ports:
    - "9200:9200"
  volumes:
    - ./esdata:/data
    - ./elastic/plugins:/plugins
    - ./elastic/conf:/usr/share/elasticsearch/config
  environment:
    - neo4j="http://neo4j"
